scalaVersion := "3.2.1"
libraryDependencies += "com.zhranklin" %% "scala-tricks" % "0.2.1" cross CrossVersion.for3Use2_13
libraryDependencies += "com.lihaoyi" % "ammonite-ops" % "2.4.0-23-76673f7f" cross CrossVersion.for3Use2_13
libraryDependencies += "com.flipkart.zjsonpatch" % "zjsonpatch" % "0.4.11"
libraryDependencies += "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.8.11"
libraryDependencies += "com.lihaoyi" % "os-lib" % "0.8.0" cross CrossVersion.for3Use2_13
libraryDependencies += "org.springframework" % "spring-core" % "5.1.7.RELEASE"
libraryDependencies += "org.fusesource.jansi" % "jansi" % "2.2.0"
libraryDependencies += "io.github.java-diff-utils" % "java-diff-utils" % "4.5"
//libraryDependencies += "io.circe" %% "circe-core" % "0.14.1"
//libraryDependencies += "io.circe" %% "circe-optics" % "0.14.1" % CrossVersion.for3Use2_13
//libraryDependencies += "io.circe" %% "circe-parser" % "0.14.1"
//libraryDependencies += "io.circe" %% "circe-yaml" % "0.14.1"
libraryDependencies += "com.github.scopt" %% "scopt" % "4.0.1" cross CrossVersion.for3Use2_13
libraryDependencies += "org.yaml" % "snakeyaml" % "1.17"
libraryDependencies += "org.slf4j" % "slf4j-log4j12" % "1.7.25"
libraryDependencies += "org.apache.httpcomponents" % "httpclient" % "4.5.2"
libraryDependencies += "org.codehaus.jackson" % "jackson-core-asl" % "1.8.7"
libraryDependencies += "log4j" % "log4j" % "1.2.17"
libraryDependencies += "joda-time" % "joda-time" % "2.1"
libraryDependencies += "org.slf4j" % "slf4j-api" % "1.7.25"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.6"
libraryDependencies += "org.bouncycastle" % "bcprov-jdk15on" % "1.60"
libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.7"
libraryDependencies += "com.lihaoyi" %% "mainargs" % "0.3.0" cross CrossVersion.for3Use2_13
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.1.1"
