FROM BASE_IMAGE
ENV TZ=Asia/Shanghai LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8
ENV JAVA_OPTS="-Dfile.encoding=UTF-8"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ARG TARGETARCH
ARG proxy
ENV opt_proxy=$proxy
RUN \
echo deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free > /etc/apt/sources.list && \
echo deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free >> /etc/apt/sources.list && \
echo deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free >> /etc/apt/sources.list && \
echo deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y vim less qrencode jq make && rm -rf /var/lib/apt/lists/* && apt-get clean
RUN bash -c "http_proxy=$opt_proxy https_proxy=$opt_proxy wget https://github.com/antonmedv/fx/releases/download/24.0.0/fx_linux_$TARGETARCH -O /usr/local/bin/fx && chmod +x /usr/local/bin/fx"
RUN bash -c "http_proxy=$opt_proxy https_proxy=$opt_proxy wget https://github.com/mikefarah/yq/releases/download/v4.21.1/yq_linux_$TARGETARCH.tar.gz -O - | tar xz && mv yq_linux_$TARGETARCH /usr/bin/yq"
RUN (echo "#!/usr/bin/env sh" && http_proxy=$opt_proxy https_proxy=$opt_proxy wget -O - https://github.com/lihaoyi/Ammonite/releases/download/2.5.4/3.1-2.5.4) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm
RUN mkdir -p /root/.ammonite
ENV COURSIER_REPOSITORIES=https://maven.aliyun.com/nexus/content/groups/public/
RUN http_proxy=$opt_proxy https_proxy=$opt_proxy wget -O - https://github.com/zhranklin/easy_kubectl/archive/1.0.21.tar.gz \
    | tar xzO easy_kubectl-1.0.21/install.sh > /usr/local/bin/easy_kubectl.sh \
    && chmod +x /usr/local/bin/easy_kubectl.sh \
    && http_proxy=$opt_proxy https_proxy=$opt_proxy wget -O - https://github.com/junegunn/fzf/releases/download/0.24.3/fzf-0.24.3-linux_$TARGETARCH.tar.gz | tar xzO > /usr/local/bin/fzf \
    && chmod +x /usr/local/bin/fzf